# Generated by Django 2.1.5 on 2019-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190202_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudyrating',
            name='rating_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating_2',
            field=models.IntegerField(default=0),
        ),
    ]
