# Generated by Django 2.1.5 on 2019-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190202_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
