# Generated by Django 2.1.5 on 2019-05-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190503_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingValues',
            new_name='RatingValue',
        ),
    ]
