# Generated by Django 2.1.5 on 2019-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190503_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudyrating',
            name='name',
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='serial_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userstudyrating',
            name='years_musical_training',
            field=models.CharField(default='', max_length=10),
        ),
    ]
