# Generated by Django 2.1.5 on 2019-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190505_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudyrating',
            name='general_a',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='general_b',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='general_c',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
