# Generated by Django 2.1.5 on 2019-05-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190506_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstudyrating',
            old_name='musical_culture',
            new_name='music_style',
        ),
    ]
