# Generated by Django 2.1.5 on 2019-05-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20190506_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudyrating',
            name='email',
        ),
    ]
