# Generated by Django 2.1.5 on 2019-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_userstudyrating_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudyrating',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='note',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
