# Generated by Django 2.1.5 on 2019-06-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20190512_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudyrating',
            name='rating1_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating1_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating1_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating2_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating2_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating2_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating3_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating3_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating3_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating4_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating4_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating4_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating5_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating5_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstudyrating',
            name='rating5_5',
            field=models.IntegerField(default=0),
        ),
    ]
